apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - image: santoshr1016/argoapp
          name: sample-app
          ports:
            - containerPort: 3100
          envFrom:
            - configMapRef:
                name: sample-configmap