apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/santoshr1016/squish-argo.git
    targetRevision: HEAD
    path: sample-app-k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false